### ISSUE TITLE
Error when saving pinboard API key

### ISSUE THREAD

**Issue by pspinler** [seeba8/yet-another-pinboard-extension#42]
When I attempt to save my API key in the extension preferences screen, a small red triangle appears with the popup text "Internal Server Error".

In the browser console, I find the error "Error: Promised response from onMessage listener at init@moz-extension://3e4d4171-6884-1541-9874-1f48df3afc85/dist/browser-core.js:24482:5 went out of scope"

Firefox ver 59.0.1 on OSX 10.13.3

**Comment by seeba8** [comment]
Sounds like either a latency issue or some serverside hiccup to me. Maybe try restarting Firefox and re-entering the api key.
If it still does not work then, could you open the console first, go to the network tab of it, and then re-save the API key? Then you should be able to monitor if the packet is sent properly and you get a reply.

**Comment by pspinler** [comment]
Restarted firefox, retried, still same error.

Opened browser console again, set the "Net" menu dropdown to "Log", and observed that it logged other net traffic.  However, when I again attempt to re-save API key in the pinboard preferences screen; I see _no_, net activity logged in the console.  That is, there doesn't appear to be anything reaching out.

I also tried this after disabling all my other extensions, still with the same error.

Any other debugging I could help with?  Any extension specific debugging or logging I could enable? Perhaps do a shared screen session via teamviewer or google hangouts? 

-- Pat

**Comment by seeba8** [comment]
Yep we can try that. I just need to finish some uni stuff I'm working on, should take me maybe 15 minutes.
If you want to do it now, that is. 
One more thing you could check yourself: go to about:debugging, click on Debug next to this addon and check if the info there is anything else.  

It has been a while since I touched that code :o

**Comment by pspinler** [comment]
Sounds cool, and I'm glad to help.  I really like the sidebar in this extension. :) 

Hangouts message me at pspinler at gmail dot com when you're ready.  I'm just hanging out and hacking on some other code for the rest of the day.

**Comment by seeba8** [comment]
Rest of the day he says. It's 10.30pm here :p

Will do. You can edit your comment if you want to remove your mail, I've copied it out.

**Comment by pspinler** [comment]
Heh -- I can't help it if people live in sane and neat places in Europe instead of someplace where we still get snow in April in north central U.S. ... :S :)

**Comment by seeba8** [comment]
Last year it was snowing here too in early May. This year is better, we had 20°C today (whatever that is in your units, but basically tshirt weather, cf https://xkcd.com/526/). So, enough chatted, will contact you in a bit, just need to finish my stuff...

**Comment by seeba8** [comment]
Ok, the resolution is: make sure that the API key is in the form seeba:12436874ABC
Note to self: Show that in the textbox hints and check for the colon!

**Comment by seeba8** [comment]
@pspinler I might or might not have pushed a new version fixing that issue ;-)
Fixed by b48c87a.

**Comment by pspinler** [comment]
Drat.  There go my dreams of git pull request patch fame ... :)

-- Pat
