### ISSUE TITLE
Keybinding for show/hide sidebar interferes with text input/editing.

### ISSUE THREAD

**Issue by LiamFry** [seeba8/yet-another-pinboard-extension#52]
Is there a way to change the keybinding used for showing/hiding the sidebar?
Using SH-ALT-(left) interferes with text selection/editing in text input boxes.
For example, while I'm typing this, if I need to replace the previous word as I type, I would hit SH-ALT-(left) to highlight and move back a word. This editing action works but it *also* toggles the sidebar. If I do it again, it toggles the sidebar again. Do the SH-ALT-(left) for several words and the sidebar keeps blinking into and out of existence.
I would really like to change the keybinding for show/hide sidebar.

**Comment by seeba8** [comment]
Whoops I did not think of that! You can change keybinds for (all) addons the following way yourself:
- In Firefox, open the extensions page (e.g. going to `about:addons`) and click on the cogwheel at the top right (it's next to `Manage Your Extensions`). Then, click on Manage Extension Shortcuts
- In Chrome, open the extensions window, click the sandwich menu in the top left and change to Keyboard shortcuts. Alternatively, this link should work too: `chrome://extensions/shortcuts`

I'll update the addon sometime soon, hopefully finding a keybind that isn't already in use.

**Comment by LiamFry** [comment]
I did not know that could be done; thank you!  BTW, love your extension; and _thank you for that_.
