### ISSUE TITLE
Searching by prepending `pin` in the omnibar doesn't work in 1.5.0

### ISSUE THREAD

**Issue by benoitlouy** [seeba8/yet-another-pinboard-extension#62]
I used to be able to type `pin keyword` in the omnibar and search results containing `keyword` would appear in the results.
After the extension was upgraded to version 1.5.0 this doesn't work anymore.

**Comment by seeba8** [comment]
Whoops, that must have slipped my testing. I can confirm the regression, I can't search like that either. My bad. I'll try to fix it as quickly as possible.

**Comment by seeba8** [comment]
The fixed version is already on addons.mozilla.org, and will hopefully be approved in the chrome store soon too.
